import type { IconType } from "react-icons";
import {
    SiJavascript,
    SiTypescript,
    SiCplusplus,
    SiSharp,
    SiPython,
    SiReact,
    SiNextdotjs,
    SiExpress,
    SiNodedotjs,
    SiTailwindcss,
    SiHtml5,
    SiCss,
    SiMysql,
    SiMongodb,
    SiSqlite,
    SiGit,
    SiGithub,
    SiFigma,
    SiVercel,
    SiAndroidstudio,
    SiUnity,
    SiGodotengine,
} from 'react-icons/si';
import { DiJava } from 'react-icons/di';
import type { SkillLevel } from "@/types/content";

export const skillIconMap: Record<string, IconType> = {
    javascript: SiJavascript,
    typescript: SiTypescript,
    java: DiJava,
    cplusplus: SiCplusplus,
    csharp: SiSharp,
    python: SiPython,
    react: SiReact,
    nextjs: SiNextdotjs,
    express: SiExpress,
    nodejs: SiNodedotjs,
    tailwindcss: SiTailwindcss,
    html: SiHtml5,
    css: SiCss,
    mysql: SiMysql,
    mongodb: SiMongodb,
    sqlite: SiSqlite,
    git: SiGit,
    github: SiGithub,
    figma: SiFigma,
    vercel: SiVercel,
    androidstudio: SiAndroidstudio,
    unity: SiUnity,
    godot: SiGodotengine,
};

export const skillLevelLabel: Record<SkillLevel, string> = {
    1: 'Beginner',
    2: 'Beginner',
    3: 'Intermediate',
    4: 'Advanced',
    5: 'Expert',
};